export const CATEGORY_ICON_NAMES = [
  "tag",
  "utensils",
  "coffee",
  "shopping-bag",
  "shirt",
  "car-front",
  "bus",
  "fuel",
  "house",
  "receipt-text",
  "wifi",
  "smartphone",
  "heart-pulse",
  "pill",
  "graduation-cap",
  "book-open",
  "gamepad-2",
  "dumbbell",
  "music",
  "plane",
  "baby",
  "gift",
  "briefcase-business",
  "banknote-arrow-up",
  "wallet-cards",
  "rotate-ccw",
  "banknote",
  "circle-help",
  "apple",
  "beer",
  "cake-slice",
  "cooking-pot",
  "pizza",
  "salad",
  "sandwich",
  "luggage",
  "train-front",
  "bike",
  "truck",
  "building-2",
  "landmark",
  "coins",
  "credit-card",
  "piggy-bank",
  "key-round",
  "stethoscope",
  "tooth",
  "construction",
  "hammer",
  "palette",
  "film",
  "headphones",
  "trophy",
  "camera",
  "map-pin",
  "clock-3",
] as const;

export type CategoryIconName = (typeof CATEGORY_ICON_NAMES)[number];

export const DEFAULT_CATEGORY_ICON: CategoryIconName = "tag";

export const CATEGORY_ICON_LABELS: Record<CategoryIconName, string> = {
  tag: "Catégorie",
  utensils: "Nourriture",
  coffee: "Café",
  "shopping-bag": "Shopping",
  shirt: "Vêtements",
  "car-front": "Voiture",
  bus: "Transport",
  fuel: "Carburant",
  house: "Maison",
  "receipt-text": "Facture",
  wifi: "Internet",
  smartphone: "Téléphone",
  "heart-pulse": "Santé",
  pill: "Médicaments",
  "graduation-cap": "Éducation",
  "book-open": "Livres",
  "gamepad-2": "Jeux",
  dumbbell: "Sport",
  music: "Musique",
  plane: "Voyage",
  baby: "Enfant",
  gift: "Cadeau",
  "briefcase-business": "Travail",
  "banknote-arrow-up": "Salaire",
  "wallet-cards": "Portefeuille",
  "rotate-ccw": "Remboursement",
  banknote: "Argent",
  "circle-help": "Autre",
  apple: "Alimentation",
  beer: "Boissons",
  "cake-slice": "Pâtisserie",
  "cooking-pot": "Cuisine",
  pizza: "Pizza",
  salad: "Salade",
  sandwich: "Sandwich",
  luggage: "Bagages",
  "train-front": "Train",
  bike: "Vélo",
  truck: "Camion",
  "building-2": "Bâtiment",
  landmark: "Institution",
  coins: "Pièces",
  "credit-card": "Carte bancaire",
  "piggy-bank": "Tirelire",
  "key-round": "Clé",
  stethoscope: "Consultation",
  tooth: "Dentiste",
  construction: "Travaux",
  hammer: "Bricolage",
  palette: "Création",
  film: "Film",
  headphones: "Audio",
  trophy: "Réussite",
  camera: "Photo",
  "map-pin": "Lieu",
  "clock-3": "Temps",
};

export function isCategoryIconName(value: string | null | undefined): value is CategoryIconName {
  return value != null && (CATEGORY_ICON_NAMES as readonly string[]).includes(value);
}

export function normalizeCategoryIcon(value: string | null | undefined): CategoryIconName {
  return isCategoryIconName(value) ? value : DEFAULT_CATEGORY_ICON;
}
