import {
  Baby,
  Apple,
  Banknote,
  BanknoteArrowUp,
  BookOpen,
  BriefcaseBusiness,
  Bus,
  CarFront,
  CircleHelp,
  Clock3,
  Beer,
  Bike,
  Building2,
  CakeSlice,
  Camera,
  Coins,
  Coffee,
  Construction,
  CookingPot,
  CreditCard,
  Film,
  Dumbbell,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartPulse,
  Hammer,
  Headphones,
  House,
  KeyRound,
  Landmark,
  Luggage,
  Laptop,
  MapPin,
  Music,
  Palette,
  PartyPopper,
  PiggyBank,
  Pizza,
  Pill,
  Plane,
  ReceiptText,
  RotateCcw,
  Shirt,
  Salad,
  Sandwich,
  ShoppingBag,
  Sparkles,
  Smartphone,
  Stethoscope,
  Smile,
  TrainFront,
  Truck,
  Trophy,
  Tag,
  Utensils,
  WalletCards,
  Wifi,
  UsersRound,
  WashingMachine,
  type LucideIcon,
} from "lucide-react-native";
import type { ComponentProps } from "react";
import {
  normalizeCategoryIcon,
  type CategoryIconName,
} from "@/constants/category-icons";

export {
  CATEGORY_ICON_LABELS,
  CATEGORY_ICON_NAMES,
  DEFAULT_CATEGORY_ICON,
  isCategoryIconName,
  normalizeCategoryIcon,
} from "@/constants/category-icons";
export type { CategoryIconName } from "@/constants/category-icons";

type CategoryIconProps = ComponentProps<LucideIcon> & {
  name: string | null | undefined;
};

const ICONS: Record<CategoryIconName, LucideIcon> = {
  tag: Tag,
  utensils: Utensils,
  coffee: Coffee,
  "shopping-bag": ShoppingBag,
  shirt: Shirt,
  "car-front": CarFront,
  bus: Bus,
  fuel: Fuel,
  house: House,
  "receipt-text": ReceiptText,
  wifi: Wifi,
  smartphone: Smartphone,
  laptop: Laptop,
  "heart-pulse": HeartPulse,
  pill: Pill,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  "gamepad-2": Gamepad2,
  dumbbell: Dumbbell,
  music: Music,
  plane: Plane,
  baby: Baby,
  "users-round": UsersRound,
  gift: Gift,
  "party-popper": PartyPopper,
  "briefcase-business": BriefcaseBusiness,
  "banknote-arrow-up": BanknoteArrowUp,
  "wallet-cards": WalletCards,
  "rotate-ccw": RotateCcw,
  banknote: Banknote,
  "circle-help": CircleHelp,
  apple: Apple,
  beer: Beer,
  "cake-slice": CakeSlice,
  "cooking-pot": CookingPot,
  "washing-machine": WashingMachine,
  pizza: Pizza,
  salad: Salad,
  sandwich: Sandwich,
  luggage: Luggage,
  "train-front": TrainFront,
  bike: Bike,
  truck: Truck,
  "building-2": Building2,
  landmark: Landmark,
  coins: Coins,
  "credit-card": CreditCard,
  "piggy-bank": PiggyBank,
  "key-round": KeyRound,
  stethoscope: Stethoscope,
  tooth: Smile,
  construction: Construction,
  hammer: Hammer,
  palette: Palette,
  sparkles: Sparkles,
  film: Film,
  headphones: Headphones,
  trophy: Trophy,
  camera: Camera,
  "map-pin": MapPin,
  "clock-3": Clock3,
};

export function CategoryIcon({ name, ...props }: CategoryIconProps) {
  const Icon = ICONS[normalizeCategoryIcon(name)];
  return <Icon {...props} />;
}
